---
- name: Check redis mode
  fail:
    msg: "redis_type must be one of ['standalone', 'sentinel', 'cluster']"
  when: redis_mode not in ['standalone', 'sentinel', 'cluster']

- name: Create Redis directory
  file:
    path: "{{ redis_generated_dir }}"
    state: directory

- name: Generate Redis CA
  command: '{{ item.command }}'
  args:
    creates: "{{ item.creates }}"
  loop:
    - command: 'openssl genrsa -aes256 -out {{ redis_ca_root_key_file }} -passout pass:redis123 4096'
      creates: '{{ redis_ca_root_key_file }}'
      title: Generate Redis CA key
    - command: 'openssl req -x509 -passin pass:redis123 -new -nodes -key {{ redis_ca_root_key_file }} -sha256 -days 1826 -out {{ redis_ca_root_certificate_file }} -subj "{{ cert_subject }}Redis CA"'
      creates: '{{ redis_ca_root_certificate_file }}'
      title: Generate Redis CA cert
  loop_control:
    label: "{{ item.title }}"

- name: Generate Redis certs
  command: '{{ item.command }}'
  args:
    creates: "{{ item.creates }}"
  loop:
    - title: Generate Redis key and csr
      command: 'openssl req -new -nodes -out {{ redis_cert_csr_file }} -newkey rsa:4096 -keyout {{ redis_cert_private_key_file }} -subj "{{ cert_subject }}localhost" -addext "subjectAltName = {{ subject_alt_name }}"'
      creates: "{{ redis_cert_private_key_file }}"
    - title: Generate Redis cert
      command: 'openssl x509 -req -passin pass:redis123 -in {{ redis_cert_csr_file }} -CA {{ redis_ca_root_certificate_file }} -CAkey {{ redis_ca_root_key_file }} -CAcreateserial -out {{ redis_cert_certificate_file }} -days 730 -sha256'
      creates: "{{ redis_cert_certificate_file }}"
  loop_control:
    label: "{{ item.title }}"
  vars:
    subject_alt_name: "{{ ', '.join(sans) }}"

- name: Set permissions on Redis key
  file:
    path: "{{ redis_cert_private_key_file }}"
    state: file
    mode: "0644"

- name: Render Redis Configs
  template:
    src: "{{ item }}.j2"
    dest: "{{ redis_generated_dir }}/{{ item }}"
    mode: '0644'
  loop:
    - redis.conf
    - redis-sidecar.conf
    - "redis-users.acl"

- name: Zero out volume directories
  include_tasks: volume_dirs.yml
  loop: "{{ query('sequence', 'start=1 end='+(redis_node_count)|string) }}"
  vars:
    volume_type: "redis"

- name: Perform sentinel actions
  include_tasks: redis_sentinel.yml
  when: redis_mode == 'sentinel'

- name: Perform cluster actions
  include_tasks: redis_cluster.yml
  when: redis_mode == 'cluster'
