"""
Django settings for project aap_gateway_api.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import socket
from os import path
from pathlib import Path

# AAP_DEPLOYMENT_TYPE indicates the type of deployment
# "self-managed" (default), "managed-azure", or "saas-aws"
AAP_DEPLOYMENT_TYPE = "self-managed"

ALLOWED_HOSTS = ["*"]

# This setting should not be overrideable
AOC_UNCHANGEABLE_PREFERENCES = ['gateway_token_name']

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Use our own user model
AUTH_USER_MODEL = 'aap_gateway_api.User'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

CACHES = {
    "default": {
        "BACKEND": "ansible_base.lib.cache.redis_cache.DABRedisCache",
        "LOCATION": "unix:///var/run/redis/redis.sock?db=4",
        "KEY_PREFIX": "gateway",
    },
    "legacy": {
        "BACKEND": "ansible_base.lib.cache.fallback_cache.DABCacheWithFallback",
    },
    "primary": {
        "BACKEND": "django_redis.cache.RedisCache",
        # Note, the location is not really used but we parse it in the client to get settings like host/port/username/etc.
        "LOCATION": '',
        "KEY_PREFIX": 'gateway',
        "OPTIONS": {
            "CLIENT_CLASS": "ansible_base.lib.redis.RedisClient",
            "CLIENT_CLASS_KWARGS": {
                "mode": 'standalone',
                'redis_hosts': '',
                'ssl': True,
                'ssl_keyfile': '/etc/ansible-automation-platform/gateway/redis.key',
                'ssl_certfile': '/etc/ansible-automation-platform/gateway/redis.cert',
                'ssl_cert_reqs': 'required',
                'ssl_ca_certs': '/etc/ansible-automation-platform/gateway/redis_ca.cert',
                'ssl_check_hostname': False,
                'socket_keepalive': True,
                'socket_timeout': 1,
                'socket_connect_timeout': 1,
                'cluster_error_retry_attempts': 0,
            },
        },
    },
    "fallback": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": "/var/tmp/django_cache",
    },
}

CLUSTER_HOST_ID = socket.gethostname()

# DAB auto-sync cache driver: broadcast cache invalidation to other nodes
# via dispatcherd when cache write operations occur. Requires DABRedisCache
# as the CACHES backend (see AAP-65886).
ANSIBLE_BASE_REDIS_AUTO_INVALIDATE = True
ANSIBLE_BASE_CACHE_BROADCAST_QUEUE = 'gateway_broadcast'

DISPATCHERD_MIN_WORKERS = 2
DISPATCHERD_MAX_WORKERS = 4

# Status endpoint for console.redhat.com
CRC_STATUS_URL = "https://status.redhat.com/api/v2/summary.json"

# Disallow sending csrf cookies over insecure connections
CSRF_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = []

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "DATABASE_NAME",
        "USER": "DATABASE_USER",
        "PASSWORD": "DATABASE_PASSWORD",
        "HOST": "DATABASE_HOST",
        "PORT": 5432,
        "CONN_HEALTH_CHECKS": True,
        "OPTIONS": {
            "application_name": "Django API",
        },
    }
}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DYNAMIC_PREFERENCES = {
    'REGISTRY_MODULE': 'registered_preferences',
    'ENABLE_CACHE': True,
    'ENABLE_GLOBAL_MODEL_AUTO_REGISTRATION': False,
}

# This is the hostname where the gateway API can make requests to envoy.
# This is used to make API HTTP requests from the gateway to the services that
# are configured to run behind it for operations like syncing and migration.
ENVOY_HOSTNAME = "localhost"
# Envoy buffer limits are "soft limits". Set to 250 MiB to support large container image uploads.
# Must be comfortably higher than GRPC_SERVER_MAX_RECEIVE_MESSAGE_LENGTH.
# how much higher depends on network throughput, 3 MiB higher is the absolute minimum I could set without error 413s.
ENVOY_PER_CONNECTION_BUFFER_LIMIT_BYTES = 262144000  # 250 MiB
ENVOY_VERIFY_HTTPS_CERTIFICATES = True

# Set to desired external URL (load balancer, proxy, etc.)
# Used to construct fully qualified URLs to gateway
FRONT_END_URL = ''

# Time in seconds that the gateway access tokens are valid for, can be overridden
GATEWAY_ACCESS_TOKEN_EXIPIRATION = 600
GATEWAY_CERT_FILE = '/etc/ansible-automation-platform/gateway/gateway.crt'
GATEWAY_KEY_FILE = '/etc/ansible-automation-platform/gateway/gateway.key'
GATEWAY_PATH_REWRITE_SCRIPT_FILE = '/etc/envoy/envoy-path-rewrite.lua'

GRPC_SERVER_AUTH_SERVICE_TIMEOUT = "10s"
GRPC_SERVER_MAX_RECEIVE_MESSAGE_LENGTH = (2**20) * 20  # 20 MiB, formatted <1MiB> * <num_mib>
# Do not override. Sets minimum for GRPC_SERVER_MAX_RECEIVE_MESSAGE_LENGTH
GRPC_SERVER_MAX_RECEIVE_MESSAGE_LENGTH_MIN_VALUE = (2**20) * 4
GRPC_SERVER_MAX_THREADS_PER_PROCESS = 10
GRPC_SERVER_PORT = "50051"
GRPC_SERVER_PROCESSES = 5

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dynamic_preferences',
    'django_extensions',
    'flags',
    'rest_framework',
    'ansible_base.activitystream',
    'ansible_base.authentication',
    'ansible_base.rest_filters',
    'ansible_base.api_documentation',
    'ansible_base.resource_registry',
    'ansible_base.rest_pagination',
    'ansible_base.rbac',
    'ansible_base.oauth2_provider',
    "ansible_base.feature_flags",
    'aap_gateway_api',
]

# Internationalization
LANGUAGE_CODE = 'en-us'

LOG_ROOT = '/var/log/gateway/'

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'request_audit_info_filter': {
            '()': 'ansible_base.lib.logging.filters.RequestAuditInfoFilter',
        },
        'request_id_filter': {
            '()': 'ansible_base.lib.logging.filters.RequestIdFilter',
        },
    },
    'formatters': {
        'audit_logging': {'format': '%(asctime)s %(levelname)-8s %(request_id)s %(name)s [%(source_ip)s] "%(user_agent)s" %(message)s'},
        'simple': {'format': '%(asctime)s %(levelname)-8s %(request_id)s %(name)s %(message)s'},
    },
    'handlers': {
        'console': {
            '()': 'logging.StreamHandler',
            'level': 'DEBUG',
            'formatter': 'simple',
            'filters': ['request_id_filter'],
        },
        'console_audit': {
            '()': 'logging.StreamHandler',
            'level': 'DEBUG',
            'formatter': 'audit_logging',
            'filters': ['request_id_filter', 'request_audit_info_filter'],
        },
        'file': {'class': 'logging.NullHandler', 'formatter': 'simple', 'filters': ['request_id_filter']},
        'file_audit': {'class': 'logging.NullHandler', 'formatter': 'audit_logging', 'filters': ['request_id_filter', 'request_audit_info_filter']},
    },
    'loggers': {
        'aap': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
        },
        'aap.auth_audit': {
            'handlers': ['console_audit', 'file_audit'],
            'level': 'INFO',
            'propagate': False,  # Prevent propagation to the root aap logger
        },
        'ansible_base': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
        },
        'dispatcherd': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
        },
        "django_auth_ldap": {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': True,
        },
        'py.warnings': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
        },
        'rest_framework.request': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

LOGIN_REDIRECT_URL = '/api/gateway/v1/'
LOGIN_URL = '/'

LOGOUT_ALLOWED_HOSTS = []

MIDDLEWARE = [
    'ansible_base.lib.middleware.observability.ObservabilityMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'aap_gateway_api.middleware.csrf.GatewayCSRFViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'crum.CurrentRequestUserMiddleware',
    'ansible_base.lib.middleware.logging.log_request.LogTracebackMiddleware',
    'ansible_base.lib.middleware.logging.LogRequestMiddleware',
]

# URL for customer notifications feed
NOTIFICATION_RSS_FEED_URL = "https://announcements.ansiblecloud.redhat.com/feed.atom"

# NEVER remove anything from this list.
PASSWORD_HASHERS = [
    "aap_gateway_api.authentication.hashers.OwaspRecommendedArgon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

PING_PAGE_CHECK_IGNORE_CERT = False
# Timeout in seconds for ping of DB, proxy and service ping URLs.
PING_PAGE_CHECK_TIMEOUT = 3

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'aap_gateway_api.authentication.basic_auth.LoggedBasicAuthentication',
        'aap_gateway_api.authentication.service_token_auth.ServiceTokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'ansible_base.oauth2_provider.permissions.OAuth2ScopePermission',
        'ansible_base.lib.utils.views.permissions.IsSuperuserOrAuditor',
    ],
    'EXCEPTION_HANDLER': 'aap_gateway_api.views.gateway_exception_handler',
}

ROOT_URLCONF = 'aap_gateway_api.urls'

# Seconds before sessions expire.
# Note: This setting may be overridden by database settings.
SESSION_COOKIE_AGE = 1800
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_NAME = 'gateway_sessionid'
# Disallow sending session cookies over insecure connections
SESSION_COOKIE_SECURE = True
SESSION_ENGINE = "ansible_base.lib.sessions.stores.cached_dynamic_timeout"

SPECTACULAR_SETTINGS = {
    'TITLE': 'Gateway API',
    'DESCRIPTION': 'Gateway API',
    'VERSION': 'v1',
    'SCHEMA_PATH_PREFIX': '/api/gateway/v1/',
}

STATIC_ROOT = '/opt/aap_gateway/static/'
# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# This is a gateway system account that gets created. If you change this after
# the account is created, you will need to manually update the username of the
# account to match.
#
# We use an underscore prefix to make it less likely to conflict with a real
# user.
SYSTEM_USERNAME = '_system'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            path.join(BASE_DIR, 'aap_gateway_api', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'aap_gateway_api.context_processors.version',
            ],
        },
    },
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

WSGI_APPLICATION = 'aap_gateway_api.wsgi.application'

# Observability and Profiling Settings
# ObservabilityMiddleware must be added to MIDDLEWARE manually.
# Every request gets X-Request-ID and X-API-Total-Time by default.
# Enable cProfile .prof file generation (heavy — use for debugging sessions only).
ANSIBLE_BASE_PROFILING_ENABLED = False
# Enable SQL query metrics and trace context injection (moderate overhead).
ANSIBLE_BASE_PROFILING_SQL_ENABLED = False
# Directory where cProfile .prof files are written (falls back to system temp directory).
ANSIBLE_BASE_PROFILING_CPROFILE_DIR = '/var/cprofiling/aap_gateway_api'
# URL path prefixes to exclude from profiling even when the flags are enabled.
ANSIBLE_BASE_PROFILING_EXCLUDE_PATHS = [
    '/api/gateway/v1/ping/',
    '/up',
    '/v3/discovery:',
]

# Override the ANSIBLE_BASE settings we want to
ANSIBLE_BASE_ALLOW_CUSTOM_ROLES = True
ANSIBLE_BASE_ALLOW_SINGLETON_ROLES_API = True
ANSIBLE_BASE_ALLOW_SINGLETON_TEAM_ROLES = True
ANSIBLE_BASE_ALLOW_SINGLETON_USER_ROLES = True
ANSIBLE_BASE_ALLOW_TEAM_ORG_ADMIN = False
# Rely on the remote service's RBAC enforcement instead of local checks.
# See aap_gateway_api/views/api/v1/role.py for the remote permission validation path.
ANSIBLE_BASE_ENFORCE_REMOTE_OBJECT_PERMISSIONS = False
ANSIBLE_BASE_APPS_EXCLUDE_VIEW_LIST = ['ansible_base.rbac']
ANSIBLE_BASE_AUTH_AUDIT_LOGGER_NAME = 'aap.auth_audit'
ANSIBLE_BASE_AUTHENTICATOR_CLASS_PREFIXES = [
    "ansible_base.authentication.authenticator_plugins",
]
ANSIBLE_BASE_BYPASS_ACTION_FLAGS = {'view': 'is_platform_auditor'}
ANSIBLE_BASE_MANAGED_ROLE_REGISTRY = {
    'platform_auditor': {'name': 'Platform Auditor', 'shortname': 'sys_auditor'},
    'team_member': {},
    'team_admin': {},
    'org_admin': {},
    'org_member': {},
}
ANSIBLE_BASE_ORGANIZATION_MODEL = 'aap_gateway_api.Organization'
ANSIBLE_BASE_PRODUCT_NAME = 'Jewel'
ANSIBLE_BASE_PRODUCT_VERSION_FUNCTION = 'aap_gateway_api.version.get_api_version'
ANSIBLE_BASE_RESOURCE_CONFIG_MODULE = "aap_gateway_api.resource_api"
ANSIBLE_BASE_ROLE_PRECREATE = {}  # managed roles are created in data migrations
ANSIBLE_BASE_SETTINGS_FUNCTION = 'aap_gateway_api.utils.preferences.get_setting'
ANSIBLE_BASE_SOCIAL_AUTH_STRATEGY_SETTINGS_FUNCTION = "aap_gateway_api.authentication.util.load_social_auth_settings"
ANSIBLE_BASE_TEAM_MODEL = 'aap_gateway_api.Team'
ANSIBLE_BASE_USER_VIEWSET = 'aap_gateway_api.views.UserViewSet'

# Set the maximum number of secrets that can be active for a service cluster at any given time.
MAX_ACTIVE_KEYS_PER_SERVICE = 2

# This should not make a behavioral difference, but telling DAB that we do not
# want to sync resources back to another server will silence some error logs we do not want
RESOURCE_SERVER_SYNC_ENABLED = False

# Runtime feature flag settings
RUNTIME_FEATURE_FLAGS = True

SDS_CLUSTER_NAMES = ["gateway-control-plane-rest"]
SDS_REFRESH_DELAY_PROTOBUF_DURATION = "5s"

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# This is the number of hops that are trusted by envoy (proxy that we configure that sits in front of the gateway)
# This is needed for envoy to not strip the X_FORWARDED_PROTO header, which we need to determine if requests were made with https
XDS_XFF_NUM_TRUSTED_HOPS = 0
